from io import BytesIO
from typing import List
from docx import Document
from pptx import Presentation
from pptx.util import Inches, Pt

def assemble_docx(title: str, sections: List[dict]) -> bytes:
    doc = Document()
    doc.add_heading(title, level=1)
    for s in sections:
        if s.get("title"):
            doc.add_heading(s.get("title"), level=2)
        if s.get("content"):
            doc.add_paragraph(s.get("content"))
    bio = BytesIO()
    doc.save(bio)
    bio.seek(0)
    return bio.read()

def assemble_pptx(title: str, sections: List[dict]) -> bytes:
    prs = Presentation()
    # Title slide
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    title_shape = slide.shapes.title
    subtitle = slide.placeholders[1]
    title_shape.text = title
    subtitle.text = "Generated by AI Authoring Platform"

    for s in sections:
        layout = prs.slide_layouts[1]  # title and content
        slide = prs.slides.add_slide(layout)
        title_shape = slide.shapes.title
        body = slide.shapes.placeholders[1].text_frame
        title_shape.text = s.get("title") or ""
        content = s.get("content") or ""
        # naive bullet splitting by sentences
        for line in content.split(". "):
            if not line.strip():
                continue
            p = body.add_paragraph()
            p.text = line.strip()
            p.level = 0
    bio = BytesIO()
    prs.save(bio)
    bio.seek(0)
    return bio.read()
